export const THEMES = {
  1: {
    id: "1",
    toggle: "bg-1-key-first left-0",
    "bg-main": "bg-1-bg-main",
    "bg-toggle": "bg-1-bg-toggle",
    "bg-screen": "bg-1-bg-screen",
    "key-1-bg": "bg-1-key-first",
    "key-1-shadow": "border-1-key-first-shadow",
    "key-2-bg": "bg-1-key-second",
    "key-2-shadow": "border-1-key-second-shadow",
    "key-3-bg": "bg-1-key-third",
    "key-3-shadow": "border-1-key-third-shadow",
    "text-primary": "text-1-text-keypad",
    "text-secondary": "text-1-text-main",
  },
  2: {
    id: "2",
    toggle: "bg-2-key-first left-[35%]",
    "bg-main": "bg-2-bg-main",
    "bg-toggle": "bg-2-bg-toggle",
    "bg-screen": "bg-2-bg-screen",
    "key-1-bg": "bg-2-key-first",
    "key-1-shadow": "border-2-key-first-shadow",
    "key-2-bg": "bg-2-key-second",
    "key-2-shadow": "border-2-key-second-shadow",
    "key-3-bg": "bg-2-key-third",
    "key-3-shadow": "border-2-key-third-shadow",
    "text-primary": "text-2-text-keypad",
    "text-secondary": "text-2-text-main",
  },
  3: {
    id: "3",
    toggle: "bg-3-key-first left-[70%]",
    "bg-main": "bg-3-bg-main",
    "bg-toggle": "bg-3-bg-toggle",
    "bg-screen": "bg-3-bg-screen",
    "key-1-bg": "bg-3-key-first",
    "key-1-shadow": "border-3-key-first-shadow",
    "key-2-bg": "bg-3-key-second",
    "key-2-shadow": "border-3-key-second-shadow",
    "key-3-bg": "bg-3-key-third",
    "key-3-shadow": "border-3-key-third-shadow",
    "text-primary": "text-3-text-keypad",
    "text-secondary": "text-3-text-main",
  },
};
